repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: spotless-apply
        name: Spotless (Auto fix)
        entry: ./mvnw spotless:apply
        language: system
        pass_filenames: false
        files: \.java$
      - id: spotless-check
        name: Spotless Format Check
        entry: ./mvnw spotless:check
        language: system
        pass_filenames: false
        files: \.java$
      - id: maven-compile
        name: Maven Compile Check
        entry: ./mvnw
        args: [clean, compile, test]
        language: system
        pass_filenames: false
        files: \.java$
