openapi: 3.0.4
info:
  title: Rick and Morty Challenge 5 - API
  description: API for the Rick and Morty Challenge 5
  contact:
    email: rgarcia@mobdev.cl
  version: 1.0.0
externalDocs:
  description: Find out more about the Rick and Morty Challenge 5
servers:
  - url: http://localhost:8080
    description: Development server
  - url: https://api.rickandmorty.challenge.com
    description: Production server
tags:
  - name: character
    description: Get character information and their Origin
paths:
  /api/v1/character/{id}:
    get:
      tags:
        - character
      summary: Get character information and their origin
      description: Retrieve information about a character and their origin by ID.
      operationId: getCharacterInformation
      parameters:
        - name: id
          in: path
          description: The ID of the character to retrieve information for.
          required: true
          schema:
            type: integer
            format: int32
            minimum: 1
            example: 1
      responses:
        '200':
          description: Character information retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CharacterResponse'
              examples:
                rick_sanchez:
                  summary: Rick Sanchez with origin
                  value:
                    id: 1
                    name: "Rick Sanchez"
                    status: "Alive"
                    species: "Human"
                    type: "Scientist"
                    episodeCount: 51
                    origin:
                      name: "Earth (C-137)"
                      url: "https://rickandmortyapi.com/api/location/1"
                      dimension: "Dimension C-137"
                      residents: ["Rick Sanchez", "Morty Smith"]
        '400':
          description: Bad request, invalid ID format
        '404':
          description: Character not found
        '500':
          description: Internal server error

components:
  schemas:
    CharacterResponse:
      type: object
      required:
        - id
        - name
        - status
        - species
        - type
        - episodeCount
      properties:
        id:
          type: integer
          format: int32
          description: The unique identifier of the character.
          example: 1
          minimum: 1
        name:
          type: string
          description: The name of the character.
          example: "Rick Sanchez"
          pattern: '^[a-zA-Z0-9\s\-\.]+$'
        status:
          type: string
          description: The status of the character.
          example: "Alive"
          enum: ["Alive", "Dead", "unknown"]
        species:
          type: string
          description: The species of the character.
          example: "Human"
        type:
          type: string
          description: The type of the character.
          example: "Scientist"
        episodeCount:
          type: integer
          format: int32
          description: The number of episodes the character appears in.
          example: 51
          minimum: 0
        origin:
          $ref: '#/components/schemas/OriginResponse'

    OriginResponse:
      type: object
      description: Information about the character's origin location
      properties:
        name:
          type: string
          description: The name of the origin.
          example: "Earth (C-137)"
        url:
          type: string
          format: uri
          description: The URL of the origin.
          example: "https://rickandmortyapi.com/api/location/1"
        dimension:
          type: string
          description: The dimension of the origin.
          example: "Dimension C-137"
        residents:
          type: array
          description: A list of resident names in the origin.
          items:
            type: string
            maxLength: 100
          example: ["Rick Sanchez", "Morty Smith"]
